{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units_input", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_hidden_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}], "values": {"units_input": 64, "num_hidden_layers": 2, "units_0": 128}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\rakes\\anaconda3\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\rakes\\anaconda3\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\rakes\\anaconda3\\lib\\site-packages\\keras_tuner\\tuners\\sklearn_tuner.py\", line 168, in run_trial\n    y_train = split_data(y, train_indices)\n  File \"C:\\Users\\rakes\\anaconda3\\lib\\site-packages\\keras_tuner\\tuners\\sklearn_tuner.py\", line 45, in split_data\n    raise TypeError(\nTypeError: Expected the data to be numpy.ndarray or pandas.DataFrame. Received: 0      1\n1      1\n2      1\n3      1\n4      1\n      ..\n512    0\n513    0\n514    0\n515    1\n516    1\nName: size_category, Length: 517, dtype: int64.\n"}